highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://dirkaholic.github.io
author: Dirk Pahl

# edit this section with your information
baseurl: /
title: Dirk Pahl's Resume
name: Dirk Pahl
website: dirkaholic.github.io
website_full: https://dirkaholic.github.io
github: dirkaholic
twitter: dirkaholic
google_maps: 'https://www.google.de/maps/place/Lübben+(Spreewald)'
postcode: 15907
city: Luebben
country: Germany
google_analytics: UA-31129610-1

# needed for travis-ci build
exclude: [vendor]
